name: Build & Publish to jsDelivr
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - name: Commit dist if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist || true
          git diff --quiet --cached || git commit -m "auto(build): update dist [skip ci]"
      - name: Push back to main (if any change)
        run: |
          git push || true
      - name: Purge jsDelivr cache
        run: |
          # ajuste os caminhos conforme seu repo
          curl -s "https://purge.jsdelivr.net/gh/crb8/bt-theme-mizz@main/dist/bt-overrides.mizz.v1.css"
          curl -s "https://purge.jsdelivr.net/gh/crb8/bt-core@main/dist/bt-boot.v2.js"