name: Build & Publish bt-theme-mizz (jsDelivr)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: deploy-bt-theme-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - run: npm ci
      - run: npm run build

      - name: Commit dist if changed
        id: commitdist
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist || true
          if ! git diff --quiet --cached; then
            git commit -m "auto(theme): update dist [skip ci]"
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Push back to main
        if: steps.commitdist.outputs.changed == 'true'
        run: git push

      - name: Purge jsDelivr cache
        if: steps.commitdist.outputs.changed == 'true'
        run: |
          curl -s "https://purge.jsdelivr.net/gh/crb8/bt-theme-mizz@main/dist/bt-overrides.mizz.v1.css"
          curl -s "https://purge.jsdelivr.net/gh/crb8/bt-theme-mizz@main/dist/"
